### ISSUE TITLE
圆型进度条 Circle 的插槽文档有误

### ISSUE THREAD

**Issue by ZZHJohn** [TaleLin/lin-ui-doc#123]
文档中描述的
自定义背景
通过传入slot="background"自定义中间背景图案。 注：自定义背景和文字显示不能同时设置。
`<l-circle percent='50'>
    <image src="timg.jpeg" slot='background' style="width:90rpx;height:90rpx;border-radius:50%;display:block;" />
</l-circle>`

在实际使用中不能填写"slot='background'",否则不显示。

在这里的Demo[https://github.com/TaleLin/lin-ui/blob/master/examples/pages/components/view/pages/circle/index.wxml](url)
中同样没有填写插槽名

**Comment by juzi214032** [comment]
感谢反馈 这是文档错误 会尽快修复
