### ISSUE TITLE
引入lin-ui出错，建议在文档中加以说明

### ISSUE THREAD

**Issue by CrossLee** [TaleLin/lin-ui-doc#131]
按照文档操作引入后报错：
![image](https://user-images.githubusercontent.com/4584905/105441373-6478e000-5ca3-11eb-982c-1e0405031bd7.png)

解决方法：开启增强编译

**Comment by ChenJinchuang** [comment]
附议。群里已经有很多小伙伴反应过类似基础库版本偏低、未开启增强编译、需要重启后解决报错等问题，建议在文档中加以提醒，提升用户体验。

**Comment by juzi214032** [comment]
感谢反馈，文档会增加相关说明
