### ISSUE TITLE
头像组件文档有个小地方描写错误

### ISSUE THREAD

**Issue by xxxxxu98** [TaleLin/lin-ui-doc#137]
图中设置shape属性来指定头像形状，有两种形状可选，分别为circle和squre（应为square）,详情请看图中标注
![question](https://user-images.githubusercontent.com/58069232/106384323-2bf4a700-6405-11eb-93c1-fe1770ea8afc.png)

**Comment by juzi214032** [comment]
感谢反馈

**Comment by juzi214032** [comment]
已修复
