### ISSUE TITLE
index-list组件的说明不是很清晰，不知道怎么传递content参数，想请教下

### ISSUE THREAD

**Issue by HypnosC** [TaleLin/lin-ui-doc#172]
因为实例中，用的是写死的显示字段，不知道怎么链接js获取参数，请指教

**Comment by juzi214032** [comment]
content 不是一个参数，而是一个slot，就是普通的dom节点，你想要动态化的话，用`{{}}`绑定相关变量就行了

**Comment by juzi214032** [comment]
这是小程序的基础用法，不属于lin-ui的特点，如果不是很清楚，建议阅读微信小程序文档的 slot 部分

**Comment by HypnosC** [comment]
收到 谢谢！
